name: Helm Deployment
run-name: ${{ gitea.actor }} is deploying project with helm.
on: [push]


jobs:
  Helm Deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ gitea.event_name }} event."

      - name: 'checkout repository code'
        uses: 'actions/checkout@v3'

      - name: 'Helm Lint'
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: 'helm lint ./chart'

      # - name: 'Helm Deploy'
      #   uses: WyriHaximus/github-action-helm3@v3
      #   with:
      #     exec: 'helm upgrade --install dragon-fractals ./chart --wait --atomic --namespace=default'
          #kubeconfig: '${{ secrets.KUBECONFIG }}'
          #overrule_existing_kubeconfig: "false"

      # - name: 'Deploy'
      #   uses: 'deliverybot/helm@v1'
      #   with:
      #     release: 'dragon-fractals'
      #     namespace: 'default'
      #     chart: './chart'
      #   env:
      #     KUBECONFIG_FILE: '/home/jneely/.kube/gitea-config.yaml'
