name: Helm Deployment
run-name: ${{ gitea.actor }} is deploying project with helm.
on: [push]


jobs:
  Helm Deployment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ gitea.event_name }} event."

      - name: 'checkout repository code'
        uses: 'actions/checkout@v3'

      - name: 'Helm Lint'
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: 'helm lint ./chart'

      - name: 'Helm Deploy'
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: 'helm upgrade dragon-fractals ./chart/ --install --wait --atomic --namespace=default'
          # relies on an entire working kube config file dumped into this gitea secret.
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: 'Helm List'
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: 'helm list'
          # relies on an entire working kube config file dumped into this gitea secret.
          kubeconfig: '${{ secrets.KUBECONFIG }}'
